version: "3.9"

services:

  postfix:
    #
    # @see https://hub.docker.com/r/hkdigital/postfix
    #
    #image: hkdigital/postfix
    image: hkdigital-postfix

    restart: always

    environment:
      # - MAIL_DOMAIN=mailer.example.com
      # - SMTP_USER=auth@mailer.example.com:01234567890123456789
      - MAIL_DOMAIN=mailer.yyy.zzz
      - SMTP_USER=auth@mailer.yyy.zzz:01234567890123456789

    ports:
      - "25:25"

    #
    #  Add extra host names to the containers interface configuration
    # https://github.com/compose-spec/compose-spec/blob/master/spec.md#extra_hosts    
    #
    # extra_hosts:
    #   - "some-dynamic-host.duckdns.org:127.0.0.1"
    #

    volumes:
      - ./volumes/domainkeys:/etc/opendkim/domainkeys
