version: "3.9"

services:

  postfix:
    #
    # @see https://hub.docker.com/r/hkdigital/postfix
    #
    image: hkdigital/postfix
    # image: hkdigital-postfix    # run `build-latest-image.sh` first

    restart: "no"

    environment:
      MAIL_DOMAIN: mailer.example.com
      # SMTP_USER: auth@mailer.example.com
      SMTP_PASSWORD: 12345
      # DKIM_SELECTOR: mail

    ports:
      #
      # When mapping ports in the HOST:CONTAINER format,
      # you may experience erroneous results when using a container port
      # lower than 60, because YAML parses numbers in the format xx:yy
      # as a base-60 value. For this reason, we recommend always explicitly
      # specifying your port mappings as strings.
      #
      # @see https://docs.docker.com/compose/compose-file/compose-file-v3/#ports
      #
      - "25:25"

    #
    # The domainkeys folder could contain two files:
    #
    # - mail.private    <= private key
    # - mail.txt        <= public key
    #
    # Where `mail` is the specified DKIM_SELECTOR
    #
    # Check out the Internet about how to generate a DKIM key pair and how to
    # configure DNS.
    #
    volumes:
      - ./volumes/domainkeys:/etc/opendkim/domainkeys

    #
    # To add extra host names to the containers interface configuration:
    #
    # @see https://github.com/compose-spec/compose-spec/blob/master/spec.md#extra_hosts
    #
    # extra_hosts:
    #   - "some-dynamic-host.duckdns.org:127.0.0.1"
    #
